implemented recommendations by @whetu on Reddit and did additional cleanup; tests pass

diff --git a/tinytestlib b/tinytestlib
--- a/tinytestlib
+++ b/tinytestlib
@@ -5,6 +5,11 @@
 # I eventually want to make it handle being run from either zsh or bash (and possibly
 # other shells), but for now, it's just bash.
 
+if (( BASH_VERSINFO < 4 )); then
+  printf -- '[ERROR]: %s\n' "bash v4.x or higher required" >&2
+  exit 1
+fi
+
 save_shellenv() {
   _prev_shell_opts=$(set +o; shopt -p;)
 }
@@ -15,54 +20,79 @@ restore_shellenv() {
   unset _prev_shell_opts
 }
 
-# ANSI color helpers
-red_text() {
-  echo -en "\e[31m${1}\e[0m"
-}
-
-green_text() {
-  echo -en "\e[32m${1}\e[0m"
-}
-
-yellow_text() {
-  echo -en "\e[93m${1}\e[0m"
+# Is this a TTY? Or, is one being faked for testing reasons?
+isatty() {
+  [[ -v FAKE_TTY ]] && return 0
+  [[ -t 0 && -t 1 ]] && return 0 || return 1
 }
 
 # echo has nonstandard behavior, so...
-posixy_echo_no_newline() {
-  printf "%b" "$*"
+puts() {
+  local print_fmt end_fmt print_spec newline
+  print_spec='%s'
+  newline='\n'
+  end_fmt='\e[0m'
+  while true; do
+    case "${1}" in
+      (--green)   print_fmt='\e[32m' ;;
+      (--yellow)  print_fmt='\e[93m' ;;
+      (--red)     print_fmt='\e[31m' ;;
+      (-n)        newline='' ;;
+      (-e)        print_spec='%b' ;;
+      (-en|-ne)   print_spec='%b'; newline='' ;;
+      (-E)        print_spec='%s' ;;
+      (-*)        die "Unknown format specifier: ${1}" ;;
+      (*)         break ;;
+    esac
+    shift
+  done
+
+  # If we're not interactive, override print_fmt and end_fmt to remove ansi
+  isatty || unset -v print_fmt end_fmt
+
+  # shellcheck disable=SC2059
+  printf -- "${print_fmt}${print_spec}${end_fmt}${newline}" "${*}"
 }
-posixy_echo() {
-  posixy_echo_no_newline "$*"
-  printf "\n"
+
+# ANSI color helpers
+red_text() {
+  puts --red -en "${1}"
+}
+
+green_text() {
+  puts --green -en "${1}"
+}
+
+yellow_text() {
+  puts --yellow -en "${1}"
 }
 
 hex_encode() {
-  posixy_echo_no_newline "$*" | hexdump -ve '/1 "%02x"'
+  puts -en "${*}" | hexdump -ve '/1 "%02x"'
 }
 
 hex_decode() {
   # note that using -rp instead of -r -p as args to xxd will FAIL! what's an option parser? ;)
-  posixy_echo_no_newline "$*" | xxd -r -p
+  puts -en "${*}" | xxd -r -p
 }
 
 # Captures stdout, stderr and return code of any command into the named variable (a 'declare -A var' variable name) passed as an argument.
 capture() {
   local _out _err _ret
-  if [ "$1" = "--debug" ]; then
+  if [ "${1}" = "--debug" ]; then
     local debugflag=1
     shift
   fi
-  # So this is a "name reference" (bash 4.5+). Any references to this name here will actually refer to the passed-in name on $1.
+  # So this is a "name reference" (bash 4.5+). Any references to this name here will actually refer to the passed-in name on ${1}.
   # Which should be declared in that scope as `declare -A` (associative array/dictionary).
-  local aa_alias=$1
-  declare -n outs_dict=$1
+  local aa_alias=${1}
+  declare -n outs_dict=${1}
   shift
   # check to make sure we were given an associative array
   if is_associative_array $aa_alias; then
     : # we're fine (colon is a "no-op" in Bash. TYL.)
   else
-    raise "Error: $aa_alias is not an associative array (that is, declared via 'declare -A $aa_alias')"
+    die "Error: $aa_alias is not an associative array (that is, declared via 'declare -A $aa_alias')"
   fi
 
   if [ "$#" -lt 1 ]; then
@@ -81,7 +111,7 @@ capture() {
   . <({ _err=$({ _out=$("$@"); _ret="$?"; } 2>&1; declare -p _out _ret >&2); declare -p _err; } 2>&1)
 
   if [[ -v debugflag ]]; then
-    yellow_text "\ncmd: $*" >&2
+    yellow_text "\ncmd: ${*}" >&2
     yellow_text "\nout: $_out" >&2
     yellow_text "\nerr: $_err" >&2
     yellow_text "\nret: $_ret\n" >&2
@@ -94,17 +124,17 @@ capture() {
 }
 
 # exit with red text to stderr
-raise() {
-  red_text "$1" >&2
+die() {
+  red_text "${1}" >&2
   exit ${2:-1}
 }
 
 # an encoding-agnostic way to do binary comparisons
 _compare() {
   local comp_op arg1 arg2 arg1_enc arg2_enc
-  comp_op="$1"
-  arg1="$2"
-  arg2="$3"
+  comp_op="${1}"
+  arg1="${2}"
+  arg2="${3}"
   # to tapdance around escaping, ANSI etc. issues, I just encode to hex and compare those.
   # This may or may not be necessary anymore, but it fixed issues in the past
   # Wish it didn't have to fire up a subshell though; future tweak?
@@ -149,7 +179,7 @@ _compare() {
       ttl_errors="$ttl_errors\n$(red_text "Expected: $comparison" && echo)"
       return 1
     else
-      raise "Error. Expected: $comparison"
+      die "Error. Expected: $comparison"
     fi
   fi
 }
@@ -194,32 +224,32 @@ end_test_suite() {
 }
 
 assert() {
-  _compare "$2" "$1" "$3"
+  _compare "${2}" "${1}" "${3}"
   return $?
 }
 
 assert_equal() {
-  _compare "==" "$1" "$2"
+  _compare "==" "${1}" "${2}"
   return $?
 }
 
 assert_not_equal() {
-  _compare "!=" "$1" "$2"
+  _compare "!=" "${1}" "${2}"
   return $?
 }
 
 assert_match() {
-  _compare "=~" "$1" "$2"
+  _compare "=~" "${1}" "${2}"
   return $?
 }
 
 assert_no_match() {
-  _compare "!~" "$1" "$2"
+  _compare "!~" "${1}" "${2}"
   return $?
 }
 
 is_array() {
-  local declaredtype=$(declare -p "$1" 2>/dev/null | awk '{print $2}')
+  local declaredtype=$(declare -p "${1}" 2>/dev/null | awk '{print $2}')
   case "$declaredtype" in
   -a)
     return 0
@@ -231,7 +261,7 @@ is_array() {
 }
 
 is_associative_array() {
-  local declaredtype=$(declare -p "$1" 2>/dev/null | awk '{print $2}')
+  local declaredtype=$(declare -p "${1}" 2>/dev/null | awk '{print $2}')
   case "$declaredtype" in
   -A)
     return 0
@@ -244,8 +274,8 @@ is_associative_array() {
 
 # currently only works with 1 type applied at a time
 assert_type() {
-  local vartype=$1
-  local varname=$2
+  local vartype=${1}
+  local varname=${2}
   local declaredtype=$(declare -p "$varname" | awk '{print $2}')
   case "$declaredtype" in
   -A)
@@ -267,7 +297,7 @@ assert_type() {
     assert_equal "exported" "$vartype"
     ;;
   *)
-    raise "Type assertion expected $1 for $2 but declare gave $declaredtype which is currently undefined"
+    die "Type assertion expected ${1} for ${2} but declare gave $declaredtype which is currently undefined"
     ;;
   esac
 }
@@ -280,7 +310,7 @@ strip_ansi() {
   if read -t 0; then # consume stdin
     sed -E "$ansiregex"
   else
-    posixy_echo_no_newline "$1" | sed -E "$ansiregex"
+    puts -en "${1}" | sed -E "$ansiregex"
   fi
 }
 
@@ -297,10 +327,10 @@ assert_success() {
     if [ "$TTL_COLLECTING_TESTDATA" = "true" ]; then
       ((ttl_fails++))
       ttl_abbreviated_output="$ttl_abbreviated_output$(red_text "F")"
-      ttl_errors="$ttl_errors\n$(yellow_text "assert_success failure: <$*>\nstdout: ${outs[stdout]}\nstderr: ${outs[stderr]}\nretval: ${outs[retval]}" && echo)"
+      ttl_errors="$ttl_errors\n$(yellow_text "assert_success failure: <${*}>\nstdout: ${outs[stdout]}\nstderr: ${outs[stderr]}\nretval: ${outs[retval]}" && echo)"
       return 1
     else
-      raise "$(strip_ansi "assert_success failure: <$*>\nstdout: ${outs[stdout]}\nstderr: ${outs[stderr]}\nretval: ${outs[retval]}")"
+      die "$(strip_ansi "assert_success failure: <${*}>\nstdout: ${outs[stdout]}\nstderr: ${outs[stderr]}\nretval: ${outs[retval]}")"
     fi
   fi
 }
@@ -318,10 +348,10 @@ assert_failure() {
     if [ "$TTL_COLLECTING_TESTDATA" = "true" ]; then
       ((ttl_fails++))
       ttl_abbreviated_output="$ttl_abbreviated_output$(red_text "F")"
-      ttl_errors="$ttl_errors\n$(yellow_text "assert_failure was actually successful: <$*>\nstdout: ${outs[stdout]}\nstderr: ${outs[stderr]}\nretval: ${outs[retval]}" && echo)"
+      ttl_errors="$ttl_errors\n$(yellow_text "assert_failure was actually successful: <${*}>\nstdout: ${outs[stdout]}\nstderr: ${outs[stderr]}\nretval: ${outs[retval]}" && echo)"
       return 1
     else
-      raise "$(strip_ansi "assert_failure was actually successful: <$*>\nstdout: ${outs[stdout]}\nstderr: ${outs[stderr]}\nretval: ${outs[retval]}")"
+      die "$(strip_ansi "assert_failure was actually successful: <${*}>\nstdout: ${outs[stdout]}\nstderr: ${outs[stderr]}\nretval: ${outs[retval]}")"
     fi
   fi
 }
